spring:
  application:
    name: ServiceApi
  profiles:
    active: instance1
  datasource:
    driver-class-name: ${MYSQL_DRIVER_CLASS_NAME}
    url: ${MYSQL_URL}/renyibang_service
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    hibernate:
      ddl-auto: create
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR}
      config:
        import-check:
          enabled: false
    openfeign:
      okhttp:
        enabled: true
    sentinel:
      transport:
        dashboard: ${DASHBOARD_PORT}
      http-method-specify: true
